mock/default.cfg

Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>

CP-9798: Update cfg for CentOS 7 (for review only)

---

SOURCES/squeezed-conf

Signed-off-by: David Scott <dave.scott@citrix.com>

squeezed.conf: explicitly set use-switch=false

---

Makefile.xsbuild
mock/default.cfg

Attempt to fix breakage due to use of /var/xen-mock

---

SPECS/xenopsd.spec

Xenopsd needs optcomp (soon)

---

Makefile.xsbuild

Make sure we don't cache the xen-mock dir

---

SPECS/ocaml-rrdd-plugin.spec

ocaml-rrdd-plugin: Add dependency on ocaml-xenstore-clients-devel

---

SPECS/xenvm.spec

xenvm: Add dependency on ocaml-rrdd-plugin

---

SOURCES/xenvm-bugtool1.xml
SOURCES/xenvm-bugtool2.xml
SOURCES/xenvm_diagnostics
SPECS/xenvm.spec

This was lost in the conflict when the repository moved.
/cc @euanh this has your pattern fix

Re-add xen-bugtool plugin

---

SPECS/xenvm.spec

xenvm: add xenvm_diagnostics to the %files section

---

SPECS/vhd-tool.spec

vhd-tool: don't use `make install`: it doesn't work

---

SPECS/xenopsd.spec

Update SPEC for xenopsd to include new set-domain-uuid binary

---

SPECS/vhd-tool.spec

vhd-tool: Add a new binary

---

SPECS/xenvm.spec

xenvm: Add dependency on ocaml-flock

---

SOURCES/xenopsd-watch-attr-xenstore-key.patch
SPECS/xenopsd.spec

xenopsd: Add experimental patch to watch attr Xenstore key

---

SPECS/ocaml-gnt.spec
SPECS/ocaml-mirage-profile.spec

Signed-off-by: Andrew Cooper <andrew.cooper3@citrix.com>

Upgrade to ocaml-gnt-v2.2.2

---

SPECS/ocaml-xenstore-clients.spec

ocaml-xenstore-clients: Update to 0.9.4

---

SPECS/xcp-rrdd.spec

CP-16874: xcp-rrdd: Update to 1.0.0

---

SPECS/squeezed.spec
SPECS/xcp-networkd.spec
SPECS/xcp-rrdd.spec
SPECS/xenopsd.spec

CA-211264: Re-run chkconfig on upgrade to pick up any ordering change

---

SPECS/vhd-tool.spec

Signed-off-by: Thomas Sanders <thomas.sanders@citrix.com>
(cherry picked from commit 5fbcc3ddde3b1512308d44f50e4dac085589a8f7)
Signed-off-by: Phus Lu <phus.lu@citrix.com>

CP-17743: vhd-tool: BuildRequires oasis; release v0.8.0

---

SPECS/ocaml-rrdd-plugin.spec
SPECS/ocaml-xen-api-libs-transitional.spec
SPECS/ocaml-xenops.spec

Update to stdext 2.0.0

---

SPECS/rrd-client-lib.spec

The PR brings the packaging in line with the upstream release.

rrd-client-lib: CP-18405 new minor upstream release

---

SPECS/xenopsd.spec

xenopsd: Fix changelog

---

SPECS/squeezed.spec

squeezed: Update to 0.12.2

---

SPECS/xenops-cli.spec

Update xenops-cli to 1.0.2

---

SPECS/xapi-storage-script.spec

Signed-off-by: Rob Hoes <rob.hoes@citrix.com>

xapi-storage-script: update to 0.12.2

---

mock/default.cfg

Update URLs to use the new paths in Artifactory
Signed-off-by: Marcello Seri <marcello.seri@citrix.com>

mock/default.cfg: update centos/fedora repos urls

---

mock/default.cfg

Signed-off-by: Marcello Seri <marcello.seri@citrix.com>

CP-20066: ensure builds are using latest epel snapshot
