xenopsd.spec.in
Without this, *.pyc and *.pyo files are not included in the RPM like
they should be.
Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>
=> Require python-devel so that .py files are byte-compiled

mock/default.cfg
Improve build speed by excluding various bind mounted directories that balloon
up the size of root_cache.tar.gz to a few gigabytes which then means all the
build time is spent on disk IO. (the root cache went from 2.4GB to 155MB)
Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>
=> Speed up builds (part 1)

xcp-rrdd.spec.in
This was masked by the message-switch bringing it in transitively.
Now the message-switch is using mtime, this nolonger happens.
Signed-off-by: David Scott <dave.scott@citrix.com>
=> xcp-rrdd depends on oclock

SOURCES/squeezed-conf, SOURCES/xcp-networkd-conf, SOURCES/xenopsd-64-conf, SOURCES/xenopsd-conf
This enables the plumbing so that it's (hopefully) easy to experiment with SMAPIv3 plugins.
This depends on xen-api#2221
=> Enable SMAPIv3

SPECS/ocaml-xen-api-libs-transitional.spec
=> Add oasis to buildrequires of xen-api-libs-transitional

SOURCES/xcp-rrdd-init
xcp-rrdd 655ee6959a36930fc9a0b80bfeda922e69c6978f uses the new
`Xcp_service.configure2` API which means that
-pidfile <FOO>    ==>  --pidfile <FOO>
-daemon true      ==>  --daemon true
Needs to be merged as the same time as [xapi-project/xcp-rrdd#52]
=> CP-12902: change the command-line to be more consistent

SPECS/vhd-tool.spec
=> vhd-tool: `make install` requires config.mk to exist

SOURCES/xenopsd-64-conf, SOURCES/xenopsd-conf
If a developer builds a xenopsd binary by hand then it might look for
the inventory file in the wrong place.
Signed-off-by: David Scott <dave.scott@citrix.com>
Conflicts:
SOURCES/xenopsd-conf
=> xenopsd: specify the inventory file path in the config file

SOURCES/xcp-networkd-init, SOURCES/xcp-networkd-init.upstream
This ensures that xcp-networkd is started after forkexecd, which has a start
priority of 13 (since 97cc4745 in forkexecd.git).
(Also see xapi-project/xcp-networkd#58)
=> Start xcp-networkd with priority 14

mock/site-defaults.cfg
* Keeping chroots after successful builds has little value and
increases the risk that future builds will fail because of
insufficient disk space.
* Keeping chroots after failed builds can help with debugging
build failures.   However if a failure is systematic, it should be
possible to reproduce it in another run.  If necessary, the build
can be run by hand in the chroot using `mock --shell`.   Keeping
the failed chroot in all cases just increases the chance of
running out of disk space, causing more infrastructure-related
build failures.
=> mock: Always delete mock chroots after build, regardless of outcome

SOURCES/squeezed-init, SOURCES/xenopsd-xc-init, SOURCES/xenopsd-xenlight-init
This is safe since slot 19 was unused before this, attach-static-vdis is at slot 20, and the only thing in between 19 and 22 (what these were) is v6d which has no dependency relation with xenopsd or squeezed.
=> Startup sequence: start xenopsd and squeezed before attach-static-vdis

SPECS/xenopsd.spec
This new dependency is required to build `xenopsd` with profiling. It should not do any harm if we build for the regular case.
=> xenopsd: add ocaml-bisect-ppx dependency for coverage analysis

SPECS/ocaml-xenstore-clients.spec, SPECS/squeezed.spec, SPECS/vhd-tool.spec, SPECS/xcp-networkd.spec, SPECS/xcp-rrdd.spec
This dependency is only needed when we compile for coverage profiling
but does no harm otherwise.
=> Add ocaml-bisect-ppx-devel as build dep for various pkgs to enable coverage profiling

SPECS/xcp-networkd.spec, SPECS/xenopsd.spec
This introduces  a sub package xc-cov with binaries that write coverage data to `/tmp`. The spec file depends on a new upstream release for this. Packaging relies on symlinks that pick the normal or instrumented binary.
=> xenopsd: introduce sub package for coverage analysis

SPECS/xenopsd.spec
This fixes a packaging problem that was revealed when I installed `xenopsd-xc-cov`.
`xenopsd-xc-cov` can be installed without uninstaling `xenopsd-xc` first (which I had originally assumed). This means that the sym link `xenopsd-xc` can already exist and needs to be removed before installing a
new one.
=> xenopsd: CP-17268 fix %post for xc-cov, rm existing symlink first

SPECS/vhd-tool.spec
As CA-212154 was corrected in ocaml-vhd, we bump the release number here to
document that this release is built against the updated library ocaml-vhd 0.7.3-4
=> CA-212154 vhd-tool: bump release, build against updated ocaml-vhd lib

SPECS/ocaml-rrd-transport.spec
The JSON for meta data as part of RRD files was changed in 
https://github.com/xapi-project/rrd-transport/commit/793605d4357f4f229bf229ff5e45966f27e0ef93.
=> ocaml-rrd-transport: bump 1.0.0 to 1.1.0 after change in RRD format

SPECS/ocaml-rrd-transport.spec
Install utilities to read/write rrd files as part of the -devel sub-package. These are useful for testing other code that reads and writes rrd files. The version was bumped because rrd-transport
introduces a new flag "-once" and so it is not just a matter of packaging.
This PR depends on the most recent changes for rrd-transport being accepted first and the release tagged as v1.1.1. 
=> ocaml-rrd-transport: bump to 1.1.1, install rrd{reader,writer} CP-18504

SPECS/rrd-client-lib.spec
Initial rpm spec file for rrd-client-lib. There is a corresponding tag in the repository.
=> rrd-client-lib: initial addition CP-18405

SPECS/xenopsd.spec
Xenopsd maintains new state for nested_virt, nomigrate from when a VM is first booted.
=> xenopsd: version bump after semantic changes in CP-18289

SPECS/squeezed.spec, SPECS/xcp-networkd.spec, SPECS/xcp-rrdd.spec, SPECS/xenopsd.spec
xcp-networkd usually tracks master.  These changes update the 
spec file to the latest release and make it build correctly.
=> xcp-networkd: Fix unpinned build

SPECS/rrd-client-lib.spec
This PR brings the spec file in line with recent changes to the source code that make the library compatible with the the xcp-rrdd's plugin discovery mechanism.
=> rrd-client-lib: new version 1.1.0, compatible with xcp-rrdd

SPECS/ocaml-netdev.spec
These -devel package dependencies are for runtime and should be Requires,
not BuildRequires.
=> ocaml-netdev: Fix -devel package dependencies

SPECS/ffs.spec, SPECS/xapi-storage-datapath-plugins.spec
This causes the %python_sitelib macro to work, and also
causes the Python files to be byte-compiled in the binary
package.
=> ffs, xapi-storage-datapath-plugins: BuildRequire python-devel

SPECS/ezlvm.spec, SPECS/ffs.spec, SPECS/forkexecd.spec, SPECS/message-switch.spec, SPECS/ocaml-gnt.spec, SPECS/ocaml-libvhd.spec, SPECS/ocaml-netdev.spec, SPECS/ocaml-rrd-transport.spec, SPECS/ocaml-rrdd-plugin.spec, SPECS/ocaml-tapctl.spec, SPECS/ocaml-xcp-idl.spec, SPECS/ocaml-xcp-inventory.spec, SPECS/ocaml-xcp-rrd.spec, SPECS/ocaml-xen-api-client.spec, SPECS/ocaml-xen-api-libs-transitional.spec, SPECS/ocaml-xenops.spec, SPECS/ocaml-xenstore-clients.spec, SPECS/sm-cli.spec, SPECS/squeezed.spec, SPECS/vhd-tool.spec, SPECS/xapi-storage-datapath-plugins.spec, SPECS/xapi-storage.spec, SPECS/xapi-test-utils.spec, SPECS/xcp-networkd.spec, SPECS/xcp-rrdd.spec, SPECS/xenops-cli.spec, SPECS/xenopsd.spec
%autosetup is now the recommended way to unpack sources
and apply patches automatically.  This makes pinning and
linking in Planex much easier.
=> CP18720: Switch from %setup to %autosetup

SPECS/rrd-client-lib.spec
This brings the spec file in sync with the latest upstream changes that, among other things, fix a compatibility bug with xcp-rrdd.
=> rrd-client-lib: new upstream release 1.2.0

SPECS/rrd-client-lib.spec
New upstream release. This commit will have to be cherry-picked for the trunk-pvs branch.
=> rrd-client-lib: new upstream release 1.2.1 that fixes bug for VM/SR sources CA-223651

SOURCES/xcp-rrdd-tmp, SPECS/xcp-rrdd.spec
The behaviour of xcp-rrd changes slightly: upon startup it creates
/dev/shm/metrics with rrdmetrics as a group. This gives rrd plugins a
chance to write to this directory without root credentials. The group is
created during installation.
I have tested that the RPM builds but have not yet tested that the directory is created by the tmpdir.d service at runtime.
=> xcp-rrd: create group rrdmetrics, create /dev/shm/metrics at startup CP-19068

Makefile.xsbuild
The recipe was incorrectly creating an empty file and the source ISO
creation automatically includes SRPMs from this component.
Signed-off-by: Simon Rowe <simon.rowe@eu.citrix.com>
=> CA-234637: remove creation of SOURCES/MANIFEST

SPECS/xcp-networkd.spec
Do the additional step explained in https://github.com/xenserver/xen-api-libs-specs/commit/407cc835957d067ed2f5ed33ce1877c363e7107c:
Update the SPEC file to exactly match the one in xenserver-specs.
Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>
=> xcp-networkd: update to 0.13.3

SPECS/xcp-networkd.spec, SPECS/xenopsd.spec
Update the version of `xcp-networkd`, which hasn't diverged, to match the [`ely-bugfix`](https://github.com/xenserver/xcp-networkd/tree/ely-bugfix) version, and release `xenopsd` `v0.20.0`, which has diverged from [its `ely-bugfix` version](https://github.com/xenserver/xenopsd/tree/ely-bugfix).
Most of the changes between xenopsd `v0.20.0` and `v0.17.0` are also in its [`ely-bugfix`](https://github.com/xenserver/xenopsd/tree/ely-bugfix) branch, but I had to create an completely separate changelog which lists again the common changes that happened since the two versions diverged (it lists the `ely-bugfix` changes between `v0.17.0` and `v0.17.5`), due to the linear nature of git.
=> Update xcp-networkd and xenopsd

SPECS/ocaml-xcp-idl.spec
Use a larger minor version number to ensure that the ely-bugfix version
of xcp-idl can increment the minor version number a few times before
collision.
Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>
=> Update ocaml-xcp-idl to 1.10.0

SPECS/xenopsd.spec
The sub-packages for coverage builds are ill-defined and currently not
used. We need a global policy how to define analysis builds (coverage,
memory, time, ..). This commit keeps the coverage build of xenopsd that
is installed by the xenopsd-cov sub-package.
This brings xenopsd.spec in sync with xenserver-specs/SPECS/xenopsd.spec.
=> xenopsd: remove sub-packages for coverage builds for simulator and xenlight
